### PR TITLE
completion: try to complete copy or command

### LINKED ISSUE #584: 1.9.3: File path completion in copy mode
It looks like file path completion doesn't work anymore in 1.9.3, when using copy mode:
```
$ clush -c /tmp/file[TAB][TAB]
```
doesn't complete `/tmp/filename` anymore.

Maybe a side effect of the new bash completions [introduced](https://github.com/cea-hpc/clustershell/pull/563) in 1.9.3?

### PR DESCRIPTION
**Pull request by martinetd**
When using clush -c we should try to complete local files.

When not using -c, if a taget has already been set we can also try to complete a command.
We could do like ssh and try to complete it on any node in the nodeset, but a local completion is probably good enough.

And still complete possible options but only do so if a dash was present, this is similar to what e.g. `ls` completion does

Fixes #584

### CODE REVIEW

File: bash_completion.d/clush [hunk 1]
```diff
@@ -1,16 +1,29 @@
 # clush bash completion
 #
 # to install in /usr/share/bash-completion/completions/ or ~/.local/share/bash-completion/completions/
+_clush_command_or_file() {
+	# undo our nospace setting...
+	compopt +o nospace
+
+	# complete either files (copy mode) or commands (if target set)
+	case "$target_set,$mode" in
+	*,copy) _comp_compgen_filedir;;
```
Comment (kcgthb) [inline bash_completion.d/clush:10]: Isn't `_comp_compgen_filedir` be a "recent" addition to `bash-completion`? Looks like it's been [introduced](https://github.com/scop/bash-completion/commit/6e8a1546bde205fd7064d9e578f35ec67e2c6840) in 2.12, and I think even el9 only ships `bash-completion` 2.11.
Maybe we need a more backward compatible alternative?

File: bash_completion.d/clush [hunk 2]
```diff
@@ -1,16 +1,29 @@
...
+	1,command) _comp_command_offset "$i";;
```
Comment (martinetd) [inline bash_completion.d/clush:11]: ... And this as well, renamed from _command_offset to _comp_command_offset in 2.12.0 (itself available since 1.0 so forever)

File: bash_completion.d/clush (hunk 1 above)
Comment (martinetd) [reply bash_completion.d/clush:10]: oh, good catch!
Looks like that commit just renamed `_filedir` which has been around since forever, but they didn't keep an alias for the old one so I guess we'll need to check..l

It's not too hard to check once at source time and keep the variant to use in a variable, probably better than install time check...

Comment (martinetd) [reply bash_completion.d/clush]: Done, the check takes 4~5us on my machine so just checking everytime instead of hogging a variable for this. Tested on debian stable (also bash-completon 2.11) and fedora 41 (bash-completion 2.16)

Comment (kcgthb) [reply bash_completion.d/clush]: Thanks @martinetd!

**Comment by kcgthb** [comment]
Thanks for the fix!

I know I'm being a nitpicker here, but two more minor details :)

1. nodeset/group completion works for short options only if there's a space after the option. For instance:
   - `clush -w@ log<TAB>` completes to `clush -w@ login` as expected
   - but `clush -w@log<TAB>` doesn't completes to anything (although `-w@login` is a valid syntax

2. command completion only works when it's placed before filename completion. But if `-c` happens first in the command line, then command completion doesn't work anymore. For instance, this doesn't complete the nodeset:
   ```
   $ clush -c /etc/slurm/slurm.conf -w @log<TAB>
   ```

**Comment by martinetd** [comment]
1. is unrelated to this PR, opened https://github.com/cea-hpc/clustershell/pull/586
2. fixed

In either case, we allow options to be way too complex... WTH does `clush -c file1 -w nodes file2` even work?!

Oh, combining the two patches `clush -c<tab>` doesn't properly complete file names from the start of the files; I'm tempted to say I don't care enough so just skipping... (as this involves standard bash-completion helpers, while we can lie about $cur I don't know how to re-add the `-c` prefix at the start of completions... So you won't be able to strip that space down, sorry :P)
Ah, while I'm on weird stuff things like `-vwnode` also doesn't work. I'll also leave that one as an exercise to the reader...
